import { ActionButtons } from "../../../shared";
import "./ReportTable.css";

/**
 * ReportTable
 *
 * "All reports" table for the Reports page. Column shape (Report name
 * / Type / Batch / Generated on / Generated by / Format / Action) is
 * specific to reports, so it lives inside pages/Reports rather than
 * /shared - only the generic ActionButtons piece comes from /shared.
 *
 * Row actions show view/edit/delete (no lock), matching the reference
 * design, so ActionButtons is called with showLock={false}.
 */
export default function ReportTable({ records = [], onView, onEdit, onDelete }) {
  return (
    <div className="report-table__wrap">
      <table className="report-table">
        <thead>
          <tr>
            <th>Report name</th>
            <th>Type</th>
            <th>Batch</th>
            <th>Generated on</th>
            <th>Generated by</th>
            <th>Format</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {records.map((record) => (
            <tr key={record.id}>
              <td className="report-table__name">{record.name}</td>
              <td className="report-table__nowrap report-table__type">{record.type}</td>
              <td className="report-table__nowrap">{record.batch}</td>
              <td className="report-table__nowrap">{record.generatedOn}</td>
              <td className="report-table__nowrap">{record.generatedBy}</td>
              <td>
                <span className="report-table__format-badge">{record.format}</span>
              </td>
              <td>
                <ActionButtons
                  showLock={false}
                  onView={() => onView?.(record)}
                  onEdit={() => onEdit?.(record)}
                  onDelete={() => onDelete?.(record)}
                />
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
